"""Initial migration with all tables

Revision ID: 05191b487fe1
Revises: 
Create Date: 2025-12-06 23:23:04.685417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05191b487fe1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_timestamp_start', sa.Float(), nullable=False),
    sa.Column('game_timestamp_end', sa.Float(), nullable=False),
    sa.Column('annotation_type', sa.Enum('PLAY', 'EVENT', 'NOTE', name='annotationtype'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Enum('AI', 'USER', name='createdby'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotation_timeline', 'annotations', ['game_id', 'game_timestamp_start', 'game_timestamp_end'], unique=False)
    op.create_table('game_rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_side', sa.Enum('HOME', 'AWAY', name='teamside'), nullable=False),
    sa.Column('jersey_number_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_game_player')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('game_time_offset', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_game_id', 'videos', ['game_id'], unique=False)
    op.create_index('ix_video_timeline', 'videos', ['game_id', 'game_time_offset'], unique=False)
    op.create_table('annotation_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('video_timestamp_start', sa.Float(), nullable=False),
    sa.Column('video_timestamp_end', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_id', 'video_id', name='uq_annotation_video')
    )
    op.create_table('player_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detection_tracking', 'player_detections', ['tracking_id'], unique=False)
    op.create_index('ix_detection_video_frame', 'player_detections', ['video_id', 'frame_number'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('play_type', sa.Enum('BASKET', 'MISS', 'TURNOVER', 'REBOUND', 'FOUL', 'SUBSTITUTION', 'TIMEOUT', name='playtype'), nullable=False),
    sa.Column('player_ids', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=False),
    sa.Column('points_scored', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('annotation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plays')
    op.drop_index('ix_detection_video_frame', table_name='player_detections')
    op.drop_index('ix_detection_tracking', table_name='player_detections')
    op.drop_table('player_detections')
    op.drop_table('annotation_videos')
    op.drop_index('ix_video_timeline', table_name='videos')
    op.drop_index('ix_video_game_id', table_name='videos')
    op.drop_table('videos')
    op.drop_table('game_rosters')
    op.drop_index('ix_annotation_timeline', table_name='annotations')
    op.drop_table('annotations')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
