"""Add thumbnail_path to videos

Revision ID: 3c2f03621f12
Revises: f278c83bdd7b
Create Date: 2025-12-08 12:06:52.071577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2f03621f12'
down_revision: Union[str, Sequence[str], None] = 'f278c83bdd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add thumbnail_path column - skip ALTER COLUMN for annotations (SQLite doesn't support it)
    op.add_column('videos', sa.Column('thumbnail_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_path')
    # ### end Alembic commands ###
