"""add_jersey_numbers_table

Revision ID: c7d8a3dfd4cb
Revises: 481788e17285
Create Date: 2025-12-20 08:52:45.297507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7d8a3dfd4cb"
down_revision: Union[str, Sequence[str], None] = "481788e17285"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jersey_numbers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("frame_number", sa.Integer(), nullable=False),
        sa.Column("tracking_id", sa.Integer(), nullable=False),
        sa.Column("raw_ocr_output", sa.String(length=255), nullable=False),
        sa.Column("parsed_number", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jersey_tracking", "jersey_numbers", ["tracking_id"], unique=False)
    op.create_index(
        "ix_jersey_video_frame", "jersey_numbers", ["video_id", "frame_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jersey_video_frame", table_name="jersey_numbers")
    op.drop_index("ix_jersey_tracking", table_name="jersey_numbers")
    op.drop_table("jersey_numbers")
    # ### end Alembic commands ###
